## Copyright 2024 Kaden Bilyeu (Bikatr7) (https://github.com/Bikatr7) (https://github.com/Bikatr7/kadenbilyeu.com) (https://kadenbilyeu.com)
## Use of this source code is governed by an GNU Affero General Public License v3.0
## license that can be found in the LICENSE file.

app = 'kadenbilyeu-com'
primary_region = 'iad'
swap_size_mb = 512

[build]
  dockerfile = 'build.dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = 'kb_database'
  destination = '/app/database'


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
